import { UserQuery } from "@/apis/user.serverQuery";
import { Sidebar } from "@/ui/components/Sidebar/Sidebar";
import { SidebarDefaultMenu } from "@/ui/components/Sidebar/SidebarDefaultMenu";
import { SidebarFooter } from "@/ui/components/Sidebar/SidebarFooter";
import { Show } from "@ilokesto/utilinent";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Myterview",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = new UserQuery();
  const user = await getUser();

  return (
    <div className="flex w-full flex-row-reverse">
      <main className="w-full">{children}</main>
      <Sidebar menu={<SidebarDefaultMenu />}>
        <Show when={user} fallback={""}>
          <SidebarFooter user={user} />
        </Show>
      </Sidebar>
    </div>
  );
}
