import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

export const metadata: Metadata = {
  title: "Myterview",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2', // Variable 폰트는 하나의 파일
  weight: '45 920', // 최소-최대 weight 범위
  style: 'normal',
  variable: '--font-pretendard',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`font-sans ${pretendard.variable} antialiased flex`}
      >
        {children}
      </body>
    </html>
  );
}
