import { UserQuery } from "@/apis/user.query";
import { Sidebar } from "@/components/Sidebar/Sidebar";
import { SidebarFooter } from "@/components/Sidebar/SidebarFooter";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Myterview",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = new UserQuery();
  const user = await getUser();

  if (!user) {
    redirect("/sign");
  }

  return (
    <div className="flex w-full flex-row-reverse">
      <main className="w-full">{children}</main>
      <Sidebar>
        <SidebarFooter user={user} />
      </Sidebar>
    </div>
  );
}
