import { UserQuery } from "@/api/user.serverQuery";
import { Sidebar } from "@/ui/components/Sidebar/Sidebar";
import { SidebarDefaultMenu } from "@/ui/components/Sidebar/SidebarDefaultMenu";
import { SidebarFooter } from "@/ui/components/Sidebar/SidebarFooter";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Myterview",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = new UserQuery();
  const user = await getUser();

  if (!user) {
    redirect("/sign");
  }

  return (
    <div className="flex w-full flex-row-reverse">
      <main className="w-full">{children}</main>
      <Sidebar menu={<SidebarDefaultMenu />}>
        <SidebarFooter user={user} />
      </Sidebar>
    </div>
  );
}
