import { UserQuery } from "@/apis/user.query";
import { Sidebar } from "@/components/Sidebar/Sidebar";
import { SidebarFooter } from "@/components/Sidebar/SidebarFooter";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Myterview",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = new UserQuery();
  const user = await getUser();

  console.log("user", user);

  if (!user) {
    redirect("/sign");
  }

  return (
    <div className="flex w-full flex-row-reverse">
      <main className="@container/main mx-auto h-dvh max-w-1160 flex-1 overflow-y-scroll px-40 py-100">
        {children}
      </main>
      <Sidebar>
        <SidebarFooter user={user} />
      </Sidebar>
    </div>
  );
}
